"""Generate a small make_moons dataset and write it as a Zig source file, so the
Python and Zig engines train on *identical* data.

Writes: zig/moons_data.zig   Run:  uv run scripts/gen_zig_data.py
"""

import pathlib

import numpy as np
from sklearn.datasets import make_moons

ZIG_DIR = pathlib.Path(__file__).resolve().parents[2] / "zig"


def main() -> None:
    X, y = make_moons(n_samples=40, noise=0.1, random_state=1337)
    y = y * 2 - 1  # {0,1} -> {-1,+1}

    lines = [
        "// AUTO-GENERATED by python/scripts/gen_zig_data.py — do not edit by hand.",
        "// A 40-point make_moons sample (noise=0.1, seed=1337), labels in {-1,+1}.",
        "// Same data the Python engine trains on, so the two lanes are comparable.",
        "",
        "pub const Point = struct { x1: f64, x2: f64, y: f64 };",
        "",
        f"pub const points = [_]Point{{",
    ]
    for (x1, x2), yi in zip(X, y):
        lines.append(f"    .{{ .x1 = {x1:.6f}, .x2 = {x2:.6f}, .y = {float(yi):.1f} }},")
    lines.append("};")
    lines.append("")

    out = ZIG_DIR / "moons_data.zig"
    out.write_text("\n".join(lines))
    print(f"wrote {out}  ({len(X)} points)")


if __name__ == "__main__":
    main()
