"""Export the numbers the explorable inlines, so the browser and Python agree.

Writes ``python/explorable_data.json``:

- the exact seeded training set and test grid used by ``polyreg.make_dataset``;
- Python's train/test MSE for degrees 1…30 from ``np.linalg.pinv``, which the
  JavaScript SVD in ``explorables/00c-double-descent.html`` must reproduce;
- five probe degrees called out explicitly for the parity assertion;
- the module's headline SVM / Hopfield numbers, for the explorable's side panel.

Run:  uv run scripts/export_explorable.py
"""

import _bootstrap  # noqa: F401

import json
import pathlib

import numpy as np

from kernelmem import polyreg as pr
from kernelmem.hopfield import capacity_curve, critical_alpha, glyph_patterns, hebbian_weights
from kernelmem.lift import phi_quadratic
from kernelmem.svm import DualSVM, circles, separable_blobs

OUT = pathlib.Path(__file__).resolve().parents[1] / "explorable_data.json"
DEGREES = list(range(1, 31))
PROBES = [3, 10, 19, 25, 30]


def main() -> None:
    x, y, xt, yt = pr.make_dataset()
    sw = pr.sweep(x, y, xt, yt, DEGREES)

    blobs_X, blobs_y = separable_blobs()
    svm = DualSVM(kernel="linear", iters=4000).fit(blobs_X, blobs_y)

    circ_X, circ_y = circles()
    poly = DualSVM(kernel="poly", params={"degree": 2}, iters=6000).fit(circ_X, circ_y)
    w3 = (poly.alpha * circ_y) @ phi_quadratic(circ_X)

    pats, names = glyph_patterns("ATZLX")
    W = hebbian_weights(pats)

    alphas, mean_m, frac = capacity_curve(n=400, alphas=np.round(np.arange(0.04, 0.281, 0.005), 4),
                                          trials=40, seed=11)

    payload = {
        "_comment": "Generated by modules/00c-kernels-hopfield/python/scripts/export_explorable.py",
        "polyreg": {
            "seed": pr.DATA_SEED,
            "sigma": pr.SIGMA,
            "n_train": len(x),
            "truth": "sin(3x) + 0.35x",
            "x_train": [round(float(v), 12) for v in x],
            "y_train": [round(float(v), 12) for v in y],
            "n_test": len(xt),
            "degrees": DEGREES,
            "train_mse": sw["train"],
            "test_mse": sw["test"],
            "beta_norm": sw["beta_norm"],
            "probe_degrees": PROBES,
            "probe_test_mse": [sw["test"][d - 1] for d in PROBES],
        },
        "svm": {
            "n": int(len(blobs_y)),
            "w": [float(v) for v in svm.weights()],
            "b": float(svm.b),
            "margin": float(svm.margin()),
            "n_support": int(svm.support_mask().sum()),
            "alphas": [round(float(v), 9) for v in svm.alpha],
            "X": [[round(float(v), 9) for v in row] for row in blobs_X],
            "y": [int(v) for v in blobs_y],
        },
        "kernel": {
            "n": int(len(circ_y)),
            "n_support": int(poly.support_mask().sum()),
            "margin": float(poly.margin()),
            "plane_w": [float(v) for v in w3],
            "plane_b": float(poly.b),
            "X": [[round(float(v), 6) for v in row] for row in circ_X],
            "y": [int(v) for v in circ_y],
        },
        "hopfield": {
            "letters": names,
            "shape": [10, 10],
            "patterns": [[int(v) for v in row] for row in pats],
            "energies": [float(-0.5 * p @ W @ p) for p in pats],
            "capacity": {
                "n": 400,
                "alphas": [float(a) for a in alphas],
                "mean_overlap": [round(float(v), 4) for v in mean_m],
                "frac_recalled": [round(float(v), 4) for v in frac],
                "alpha_c": round(float(critical_alpha(alphas, frac)), 4),
                "theory": 0.138,
            },
        },
    }

    OUT.write_text(json.dumps(payload, indent=1))
    print(f"wrote {OUT}  ({OUT.stat().st_size} bytes)")
    print("probe degrees and Python test MSE (the JS must match these):")
    for d, v in zip(PROBES, payload["polyreg"]["probe_test_mse"]):
        print(f"  degree {d:2d}  test MSE {v:.12e}")


if __name__ == "__main__":
    main()
