//! Train the from-scratch Zig MLP on the same make_moons sample the Python lane
//! uses (zig/moons_data.zig, generated by python/scripts/gen_zig_data.py) and
//! print a loss table to stdout.
//!
//! Run:  zig run main.zig      (or: zig build run)

const std = @import("std");
const eng = @import("engine.zig");
const nn = @import("nn.zig");
const moons = @import("moons_data.zig");

const Engine = eng.Engine;
const V = eng.V;

pub fn main() !void {
    // params/model live for the whole program; the graph lives one step at a time.
    var model_arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer model_arena.deinit();
    const model_alloc = model_arena.allocator();

    var prng = std.Random.DefaultPrng.init(1337);
    const rng = prng.random();

    const sizes = [_]usize{ 2, 8, 1 };
    var model = try nn.MLP.init(model_alloc, &sizes, rng);

    const pts = moons.points;
    const N: f64 = @floatFromInt(pts.len);
    const alpha: f64 = 1e-4; // L2 regularization

    const stdout = std.debug;
    stdout.print("Zig autograd — MLP {any}, {d} params, {d} moons points\n", .{ sizes, model.nparams(), pts.len });
    stdout.print("step |    loss   | acc\n", .{});
    stdout.print("-----+-----------+------\n", .{});

    // one arena for the whole per-step graph; reset each step, memory reused.
    var step_arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer step_arena.deinit();

    const steps: usize = 100;
    var final_loss: f64 = 0;
    var final_acc: f64 = 0;

    var k: usize = 0;
    while (k < steps) : (k += 1) {
        _ = step_arena.reset(.retain_capacity);
        const sa = step_arena.allocator();

        var e = Engine.init(sa);
        try model.materialize(&e);

        // build the batch loss: mean over points of relu(1 - y*score) + L2 reg
        var loss: V = try e.value(0.0);
        var correct: usize = 0;
        for (pts) |p| {
            const x0 = try e.value(p.x1);
            const x1 = try e.value(p.x2);
            const inputs = [_]V{ x0, x1 };
            const score = try model.forward(&e, sa, &inputs);

            // svm max-margin: relu(1 - y*score)
            const y = try e.value(p.y);
            const ys = try e.mul(y, score);
            const one = try e.value(1.0);
            const margin = try e.add(one, try e.mul(try e.value(-1.0), ys));
            const li = try e.reluf(margin);
            loss = try e.add(loss, li);

            if ((p.y > 0) == (e.data(score) > 0)) correct += 1;
        }
        // divide accumulated data loss by N
        loss = try e.mul(loss, try e.value(1.0 / N));

        // L2 regularization: alpha * sum(param^2)
        var reg: V = try e.value(0.0);
        for (model.pnodes) |pn| reg = try e.add(reg, try e.powc(pn, 2.0));
        loss = try e.add(loss, try e.mul(try e.value(alpha), reg));

        try e.backward(loss);
        model.readGrads(&e);

        const lr = 1.0 - 0.9 * @as(f64, @floatFromInt(k)) / @as(f64, @floatFromInt(steps));
        model.sgdStep(lr);

        final_loss = e.data(loss);
        final_acc = @as(f64, @floatFromInt(correct)) / N;

        if (k % 10 == 0 or k == steps - 1) {
            stdout.print(" {d:>3} | {d:>9.5} | {d:>4.0}%\n", .{ k, final_loss, final_acc * 100 });
        }
    }

    stdout.print("-----+-----------+------\n", .{});
    stdout.print("FINAL loss {d:.5}  acc {d:.0}%\n", .{ final_loss, final_acc * 100 });
}
