"""Write the shared dataset — and the Python lane's answers — into Zig source.

The Zig perceptron must train on *exactly* the same 200 points as the Python
one, so the two lanes can be compared number for number. Rather than parse a
file at runtime, we emit a Zig array plus the Python results as constants, and
let the Zig program assert parity against them.

Produces:
  ../zig/data.zig

Run:  uv run scripts/gen_zig_data.py
"""

import pathlib

import _bootstrap  # noqa: F401  (sets sys.path)

from perceptron import rosenblatt
from perceptron.data import SEED, augment, separable_2d

OUT = pathlib.Path(__file__).resolve().parents[2] / "zig" / "data.zig"
N = 200
MARGIN = 0.35


def main() -> None:
    X, y = separable_2d(n=N, margin=MARGIN, seed=SEED)
    Xa = augment(X)
    run = rosenblatt.train(Xa, y, max_epochs=100)
    info = rosenblatt.novikoff_bound(Xa, y)

    lines = [
        "// AUTO-GENERATED by python/scripts/gen_zig_data.py — do not edit by hand.",
        f"// {N} linearly separable 2-D points (seed {SEED}, geometric margin ≥ "
        f"{MARGIN}),",
        "// labels in {-1,+1}. The Python lane's answers travel with the data so",
        "// main.zig can assert that both lanes agree.",
        "",
        "pub const Point = struct { x1: f64, x2: f64, y: f64 };",
        "",
        "pub const points = [_]Point{",
    ]
    for (x1, x2), yi in zip(X, y):
        lines.append(f"    .{{ .x1 = {x1:.17g}, .x2 = {x2:.17g}, "
                     f".y = {float(yi):.1f} }},")
    lines += [
        "};",
        "",
        "/// What python/scripts/train_perceptron.py produced on this data.",
        "pub const python = struct {",
        f"    pub const w = [3]f64{{ {run.w[0]:.17g}, {run.w[1]:.17g}, "
        f"{run.w[2]:.17g} }};",
        f"    pub const mistakes: usize = {run.mistakes};",
        f"    pub const epochs: usize = {run.epochs};",
        f"    pub const radius: f64 = {info['R']:.17g};",
        f"    pub const gamma: f64 = {info['gamma']:.17g};",
        f"    pub const bound: f64 = {info['bound']:.17g};",
        "};",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}  ({N} points, python mistakes={run.mistakes}, "
          f"w={run.w.round(6).tolist()})")


if __name__ == "__main__":
    main()
